import React, { useState } from 'react';
import './App.css';
import Modal from './components/Modal/Modal';

function App() {
    const [modalActive, setModalActive] = useState(false)
   
    return (
        <div className="App">
            <main>
                <button className='open-btn' onClick={() => setModalActive(!modalActive)}>Modal Window</button>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt animi nihil eos sint doloremque vel cupiditate vero nobis laborum est laudantium, dignissimos sequi, eaque voluptas impedit! Eaque, quas nihil vero doloribus inventore hic accusamus, quod, laborum quos veritatis error? Itaque, dolorum modi recusandae repudiandae error consequatur a veritatis. Quisquam consequuntur neque, accusantium asperiores suscipit error voluptatum eveniet mollitia excepturi magni facilis rem necessitatibus culpa nesciunt, cumque deleniti sequi ad delectus, qui nulla! Fuga, quidem. Esse eum recusandae itaque, aut facere alias eius temporibus quia dolorum suscipit laudantium cumque voluptatibus aliquid minima delectus quo repellendus ipsa quam obcaecati corrupti perspiciatis mollitia ab dignissimos. Aliquam aliquid eum voluptatem id dolores. Ratione expedita animi nam earum facilis beatae, blanditiis accusamus ab ducimus amet id adipisci enim possimus natus sunt. Veniam, ipsa? Perferendis reiciendis debitis est amet nesciunt repellendus quae itaque sequi nemo molestias quos quia officia voluptatibus culpa, minus animi repudiandae possimus esse non laborum quis facilis. Natus corrupti distinctio totam enim sint ex dicta cumque numquam explicabo, eum sed sit saepe atque veniam nisi tempora deleniti tempore non ut voluptas ipsum doloremque! Illo voluptatibus est rem qui, consectetur distinctio aliquam voluptate adipisci corrupti ipsum odio quam natus ab accusantium possimus consequuntur facere!</p>
            </main>
                <Modal active={modalActive} setActive={setModalActive}/>
        </div>
    )
}

export default App;
