import React, { useState } from 'react';
import './App.css';
import Menu from './components/Menu/Menu';

function App() {
    const [menuActive, setMenuActive] = useState(false)
    const items = [
        {value: "Main", href: "./main", icon: "anchor"},
        {value: "Service", href: "./service", icon: "api"},
        {value: "Shop", href: "./shop", icon: "android"},
        {value: "About", href: "./about", icon: "android"},
    ]

    return (
        <div className="App">
            <nav>
                <div className="burger-btn" onClick={() => setMenuActive(!menuActive)}>
                    <span></span>
                </div>
            </nav>
            <main>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia praesentium possimus asperiores eum, aut maiores eligendi iure est eaque, suscipit, dignissimos inventore impedit similique perspiciatis nulla voluptate officiis facere et. Modi harum nesciunt vel optio, quia voluptate laborum tempora, architecto, vero error quo quae ab commodi iusto enim corrupti sit hic fugiat. Incidunt, nobis. Doloribus obcaecati error deserunt quos fuga laborum, necessitatibus laboriosam debitis ab totam, reiciendis animi expedita laudantium dicta earum eum officia atque repudiandae quia sunt ipsam? Quidem nemo mollitia, exercitationem dolore reiciendis voluptatibus autem impedit saepe minus maiores. Sint adipisci molestias ducimus modi dolorem eaque illo distinctio aspernatur nemo magni placeat minima officia odit perferendis recusandae repellendus ipsam labore est inventore, atque natus delectus neque et? Est repellat quasi ad vitae, architecto rerum eum sint delectus voluptatibus fugiat dolor. Commodi optio harum dolorem, quam molestias eaque doloribus pariatur blanditiis dolore fuga ab fugiat aspernatur at sapiente aut explicabo sunt quod sequi labore! Dolorum ullam deserunt blanditiis neque nobis eum, rerum earum magni eligendi pariatur asperiores laudantium nam repudiandae, quibusdam dolor alias, hic ratione maxime! Sunt consequatur saepe voluptates itaque reprehenderit quibusdam impedit mollitia adipisci est quisquam, porro autem harum repellendus sint accusamus ad blanditiis cumque maiores qui amet vel velit. Debitis laboriosam placeat vel doloremque dignissimos, quod adipisci! Voluptatem veritatis, eveniet aut est facere nostrum a laborum debitis ut ipsa dolorum. Illo adipisci officiis quas. Quos aspernatur at suscipit tempore, aut, veritatis id omnis doloremque, veniam explicabo facilis labore ratione quo accusamus tenetur vero nam illo reiciendis similique! Fugiat assumenda doloribus modi eos debitis quisquam obcaecati officiis impedit quia nobis, asperiores, minus eius aperiam ab voluptatibus necessitatibus quam. Quasi aliquam magni quo odit minima cupiditate molestias quisquam saepe iure neque blanditiis facilis odio dolorem vitae, quam tempora commodi maxime quae, maiores repudiandae nesciunt nemo, consectetur officiis. Ratione.</p>
            </main>
            <Menu header="Burger Menu" items={items} active={menuActive} setActive={setMenuActive}/>
        </div>
    )
}

export default App;
