export const data = [
    {"id":1,"title":"Heidelberg Army Helicopter Base","body":"EU"},
    {"id":2,"title":"Hingurakgoda Air Force Base","body":"AS"},
    {"id":3,"title":"Atlas Brasil Cantanhede Airport","body":"SA"},
    {"id":4,"title":"Clayton Municipal Airpark","body":"NA"},
    {"id":5,"title":"Hambantota Seaplane Base","body":"AS"},
    {"id":6,"title":"El Paso International Airport","body":"NA"},
    {"id":7,"title":"Sitkinak Airport","body":"NA"},
    {"id":8,"title":"Grant County International Airport","body":"NA"},
    {"id":9,"title":"Westchester County Airport","body":"NA"},
    {"id":10,"title":"Mong Hsat Airport","body":"AS"},
    {"id":11,"title":"Kamarang Airport","body":"SA"},
    {"id":12,"title":"Cadete FAP Guillermo Del Castillo Paredes Airport","body":"SA"},
    {"id":13,"title":"Gray Army Air Field","body":"NA"},
    {"id":14,"title":"Helena Regional Airport","body":"NA"},
    {"id":15,"title":"Polyarny Airport","body":"AS"},
    {"id":16,"title":"Goondiwindi Airport","body":"OC"},
    {"id":17,"title":"Seymour Airport","body":"SA"},
    {"id":18,"title":"Sayaboury Airport","body":"AS"},
    {"id":19,"title":"Erenhot Saiwusu International Airport","body":"AS"},
    {"id":20,"title":"Lewoleba Airport","body":"AS"},
    {"id":21,"title":"Chokwé Airport","body":"AF"},
    {"id":22,"title":"Jackson-Medgar Wiley Evers International Airport","body":"NA"},
    {"id":23,"title":"Lansdowne House Airport","body":"NA"},
    {"id":24,"title":"RAF Wildenrath","body":"EU"},
    {"id":25,"title":"Hamilton Island Airport","body":"OC"},
    {"id":26,"title":"Northeast Alabama Regional Airport","body":"NA"},
    {"id":27,"title":"Pincher Creek Airport","body":"NA"},
    {"id":28,"title":"La Florida Airport","body":"SA"},
    {"id":29,"title":"Donskoye Airport","body":"EU"},
    {"id":30,"title":"Volgograd International Airport","body":"EU"},
]